version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          TZ: /usr/share/zoneinfo/America/Los_Angeles
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Unit Tests
          command: bundle exec rspec
      - run:
          name: Functional Tests
          command: if [[ $(bundle exec cat sample-with-broken-utf8.csv | ./normalizer | wc -l) -ne 8 ]]; then fail; fi
